#!/bin/bash
# This script generates 'ccswc.jar'

set -e
rm -rf bin gen
rm -f ccswc.jar
antlr3 CommonCppWithStreams.g -o gen
mkdir bin
CLASSPATH=/usr/share/java/antlr3.jar:/usr/share/java/stringtemplate.jar javac -d bin Compiler.java gen/CommonCppWithStreamsLexer.java gen/CommonCppWithStreamsParser.java
cd bin
jar cvmf ../MANIFEST.MF ../ccswc.jar -C ./ *.class
